version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ulianasavi/test-app:latest
    container_name: server
    restart: always
    command: npm run start:dev
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT
    volumes:
    - ./:/src
    links:
      - postgres
    networks:
      - app-network
  postgres:
      image: postgres:15.3
      environment:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $POSTGRES_USERNAME
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ports:
        - $POSTGRES_PORT:$POSTGRES_PORT
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      restart: always
      networks:
      - app-network
networks:
  app-network:
    name: app-network