version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: always
    command: npm run start:dev
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - "4000:4000"
  postgres:
      image: postgres:15.3
      environment:
        POSTGRES_DB: "Node-js-server"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      restart: always