version: '3'

services:
  server:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: always
    command: npm run start:dev
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT
  postgres:
      image: postgres:15.3
      environment:
        POSTGRES_DB: $DB_NAME
        POSTGRES_USER: $POSTGRES_USERNAME
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ports:
        - $POSTGRES_PORT:$POSTGRES_PORT
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      restart: always